import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className + "w-full md:w-1/2 lg:1/3 m-auto"}
        suppressHydrationWarning
      >
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
